name: vercel_cookbooks
description: Vercel Cookbooks
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_inset_shadow: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Geist
      fonts:
        - asset: assets/fonts/Geist/Geist-Regular.ttf
          weight: 400
        - asset: assets/fonts/Geist/Geist-SemiBold.ttf
          weight: 600